const path = require("path");
const REPO = path.join(process.env.USERPROFILE, "Desktop", "inkdesk");
const { chromium } = require("playwright-core");
const { signIn } = require("./look.cjs");
const { createClient } = require(path.join(REPO, "node_modules", "@supabase", "supabase-js"));
(async () => {
  const OUT = process.argv[2];
  const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
  const { data: st } = await db.from("studios").select("id").eq("slug","help").single();
  const { data: c } = await db.from("contacts").select("id,name").eq("studio_id", st.id).not("email","is",null).limit(1).single();
  const { data: owner } = await db.from("studio_members").select("user_id").eq("studio_id", st.id).limit(1);
  const b = await chromium.launch({ channel: "chrome", headless: true });
  const ctx = await b.newContext({ viewport: { width: 1280, height: 1400 } });
  const p = await signIn(ctx, owner[0].user_id, "/");
  await p.goto(process.env.SITE + "/clients/" + c.id, { waitUntil: "networkidle" });
  await p.waitForTimeout(1800);
  const txt = await p.evaluate(() => document.body.innerText);
  console.log("mentions confirmation:", /confirmation/i.test(txt));
  console.log("mentions reminder:", /reminder/i.test(txt));
  const t = txt.split("\n").filter(Boolean);
  console.log("\npage text:\n  " + t.slice(0, 40).join("\n  "));
  await p.screenshot({ path: `${OUT}/client.png`, fullPage: true });
  await b.close();
})();
